apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloappbitsdevops-deployment1
  labels:
    app: helloapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: srinijakammari/devops:latest
        imapepullpolicy:IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: helloapp
       
       
----------


apiVersion: v1
kind: Service
metadata:
  name: helloappbitsdevops-service
spec:
  selector:
    app: helloapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
  type: LoadBalancer
